name: greenwheel
description: GreenWheel app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  http: ^0.13.5
  google_maps_flutter: ^2.2.1
  flutter_config: ^2.0.0
  provider: ^6.0.4
  devicelocale: ^0.5.5
  cupertino_icons: ^1.0.5
  image_picker: ^0.8.6
  location: ^4.4.0
  firebase_core: ^2.1.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  go_router: ^5.1.1
  awesome_snackbar_content: ^0.0.8
  badges: ^2.0.3
  json_annotation: ^4.7.0
  flutter_polyline_points: ^1.0.0
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.6
  flutter_rating_bar: ^4.0.1
  material_floating_search_bar: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  json_serializable: ^6.5.3

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - langs/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages